export const routes = {
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  clients: "/clients",
  jobs: "/jobs",
  payments: "/payments",
  schedule: "/schedule",
  workforce: "/workforce",
  reports: "/reports",
  clientDetail: (id: string) => `/clients/${id}`,
  clientEdit: (id: string) => `/clients/${id}/edit`,
  clientNew: () => "/clients/new",
  jobDetail: (id: string) => `/jobs/${id}`,
  jobEdit: (id: string) => `/jobs/${id}/edit`,
  jobNew: () => "/jobs/new",
  paymentDetail: (id: string) => `/payments/${id}`,
  paymentEdit: (id: string) => `/payments/${id}/edit`,
  paymentNew: () => "/payments/new",
  scheduleDetail: (id: string) => `/schedule/${id}`,
  scheduleEdit: (id: string) => `/schedule/${id}/edit`,
  workforceDetail: (id: string) => `/workforce/${id}`,
  workforceEdit: (id: string) => `/workforce/${id}/edit`,
  workforceNew: () => "/workforce/new",
}
