export const routes = {
  // Public
  home: "/",
  login: "/login",
  register: "/register",
  // Onboarding
  onboarding: "/onboarding",
  onboardingBusinessType: "/onboarding/business-type",
  onboardingSubscription: "/onboarding/subscription",
  onboardingSetup: "/onboarding/setup",
  // App
  dashboard: "/dashboard",
  clients: "/clients",
  jobs: "/jobs",
  payments: "/payments",
  schedule: "/schedule",
  workforce: "/workforce",
  reports: "/reports",
  settings: "/settings",
  estimates: "/estimates",
  clientDetail: (id: string) => `/clients/${id}`,
  clientEdit: (id: string) => `/clients/${id}/edit`,
  clientNew: () => "/clients/new",
  jobDetail: (id: string) => `/jobs/${id}`,
  jobEdit: (id: string) => `/jobs/${id}/edit`,
  jobNew: () => "/jobs/new",
  paymentDetail: (id: string) => `/payments/${id}`,
  paymentEdit: (id: string) => `/payments/${id}/edit`,
  paymentNew: () => "/payments/new",
  scheduleDetail: (id: string) => `/schedule/${id}`,
  scheduleEdit: (id: string) => `/schedule/${id}/edit`,
  workforceDetail: (id: string) => `/workforce/${id}`,
  workforceEdit: (id: string) => `/workforce/${id}/edit`,
  workforceNew: () => "/workforce/new",
  estimateDetail: (id: string) => `/estimates/${id}`,
  estimateEdit: (id: string) => `/estimates/${id}/edit`,
  estimateNew: (jobId?: string) => jobId ? `/estimates/new?jobId=${jobId}` : "/estimates/new",
}
